#ifndef ERROR_CODES_HPP
# define ERROR_CODES_HPP

#define RPL_TOPIC "332"
#define RPL_NAMREPLY "353"
#define RPL_ENDOFNAMES "366"
#define RPL_LIST "322"
#define RPL_LISTEND "323"
#define RPL_YOUREOPER "381"
#define RPL_WELCOME "001"
#define ERR_USERONCHANNEL "443"
#define ERR_PASSWDMISMATCH "464"
#define RPL_PASSOK "381"
#define ERR_NOTREGISTERED "451"
#define ERR_NEEDMOREPARAMS "461"
#define ERR_CANNOTSENDTOCHAN "404"
#define ERR_NOSUCHNICK "401"
#define ERR_ALREADYREGISTRED "462"
#define ERR_NOPRIVILEGES "481"
#define ERR_CHANOPRIVSNEEDED "482"
#define ERR_NOTONCHANNEL "442"
#define ERR_NOSUCHCHANNEL "403"
#define RPL_NOTOPIC "331"
#define ERR_CHANOPRIVSNEEDED "482"
#define ERR_USERNOTINCHANNEL "441"
#define ERR_BADCHANMASK "476"

#endif
